export const WORDS_10LETTERSUNIQUE_2XCOOL_PL = [
  'ANTYPOLSKI', //OK 2x
  'BARTODZIEJ', //OK 2x
  'BEZLITOSNY', //OK 2x
  'BRZYDACTWO', //OK 2x
  'BURACZYSKO', //OK 2x
  'BURSZTYNEK', //OK 2x
  'BUTELCZYNA', //OK 2x
  'BUZDYGANEK', //OK 2x
  'CMENTARZYK', //OK 2x
  'DEBILOWATY', //OK 2x
  'DESTRUKCJA', //OK 2x
  'DESZYFRANT', //OK 2x
  'DOWCIPASEK', //OK 2x
  'DYSFUNKCJA', //OK 2x
  'EGZORCYSTA', //OK 2x
  'FECHMISTRZ', //OK 2x
  'FRAGMENCIK', //OK 2x
  'FUZJONISTA', //OK 2x
  'GORSZYCIEL', //OK 2x
  'GRUBASKIEM', //OK 2x
  'GRYPSUJCIE', //OK 2x
  'GWIAZDOREK', //OK 2x
  'HEBRAJCZYK', //OK 2x
  'HISTORYJKA', //OK 2x
  'INFORMATYK', //OK 2x
  'KANGURZYCO', //OK 2x
  'KASTRUJCIE', //OK 2x
  'KONSUMPCJA', //OK 2x
  'KWADRYLION', //OK 2x
  'LICZYKRUPA', //OK 2x
  'MAGNETOWID', //OK 2x
  'MARSZOBIEG', //OK 2x
  'MORDZIASTY', //OK 2x
  'NIEBURACKO', //OK 2x
  'NIEMCZYSKO', //OK 2x
  'ODPISYWACZ', //OK 2x
  'OKRYJBIEDA', //OK 2x
  'OSZUKANIEC', //OK 2x
  'PALOWNICZY', //OK 2x
  'PARKINGOWY', //OK 2x
  'PARSZYWIEC', //OK 2x
  'PASIBRZUCH', //OK 2x
  'PASKUDZTWO', //OK 2x
  'PATRYCJUSZ', //OK 2x
  'PIJACZYSKO', //OK 2x
  'PIOSENKARZ', //OK 2x
  'PLUWIOGRAF', //OK 2x
  'PODBIERACZ', //OK 2x
  'PODEJRZANY', //OK 2x
  'PODGRZYBEK', //OK 2x
  'POKERZYSTA', //OK 2x
  'PORACHUNEK', //OK 2x
  'PRAWNUCZEK', //OK 2x
  'PROSTACZEK', //OK 2x
  'PRZEBOGATY', //OK 2x
  'PRZEMYTNIK', //OK 2x
  'PRZYJACIEL', //OK 2x
  'PSEUDOBANK', //OK 2x
  'RELATYWIZM', //OK 2x
  'ROZPUSTNIK', //OK 2x
  'SOCREALIZM', //OK 2x
  'SOLIDARUCH', //OK 2x
  'SPADKOWICZ', //OK 2x
  'SPRZEDAJNY', //OK 2x
  'STRZELNICA', //OK 2x
  'SUPERGLINA', //OK 2x
  'SUPERMOCNY', //OK 2x
  'SUPERTAJNY', //OK 2x
  'SUPERWIZJA', //OK 2x
  'SZABROWNIK', //OK 2x
  'SZLACHETNY', //OK 2x
  'SZMUGLERKA', //OK 2x
  'SZPIEGOMAN', //OK 2x
  'SZTABOWIEC', //OK 2x
  'SZUBRAWIEC', //OK 2x
  'SZYBCIOREM', //OK 2x
  'TAJEMNICZY', //OK 2x
  'TECHNOKLUB', //OK 2x
  'TERMOWIZJA', //OK 2x
  'UDEPTYWACZ', //OK 2x
  'UPADOMIERZ', //OK 2x
  'UTRZYMANEK', //OK 2x
  'VOLKSWAGEN', //OK 2x
  'WESOLUCHNY', //OK 2x
  'WIELGACHNY', //OK 2x
  'WINDYKATOR', //OK 2x
  'WODZIREJKA', //OK 2x
  'WYKPIGROSZ', //OK 2x
  'ZASKRONIEC', //OK 2x
  'ZBIERACTWO', //OK 2x
  'ZIELARSTWO', //OK 2x
];
export const WORDS_10LETTERSUNIQUE_COOL_PL = [
  'AGROBIZNES', //OK
  'AGROCHEMIK', //OK
  'AMPLITUNER', //OK
  'ANTYPOLSKI', //OK 2x
  'ARCYBISKUP', //OK
  'ASTROFIZYK', //OK
  'BANKRUCTWO', //OK
  'BARTODZIEJ', //OK 2x
  'BEZCHMURNY', //OK
  'BEZLITOSNY', //OK 2x
  'BIOMETRYKA', //OK
  'BOHATERSKI', //OK
  'BRUTALNIEJ', //OK
  'BRZYDACTWO', //OK 2x
  'BUDOWNICZY', //OK
  'BURACZYSKO', //OK 2x
  'BURSZTYNEK', //OK 2x
  'BUTELCZYNA', //OK 2x
  'BUZDYGANEK', //OK 2x
  'CEBULOWATY', //OK
  'CMENTARZYK', //OK 2x
  'DEBILOWATY', //OK 2x
  'DEPUTOWANY', //OK
  'DESTRUKCJA', //OK 2x
  'DESZYFRANT', //OK 2x
  'DOKUCZLIWY', //OK
  'DOWCIPASEK', //OK 2x
  'DRUTOWNICA', //OK
  'DRZEWOSTAN', //OK
  'DUPNEGATYW', //OK
  'DWUCHLOREK', //OK
  'DYSFUNKCJA', //OK 2x
  'EGZORCYSTA', //OK 2x
  'FECHMISTRZ', //OK 2x
  'FRAGMENCIK', //OK 2x
  'FRYSZTACKI', //OK
  'FURGONETKA', //OK
  'FUZJONISTA', //OK 2x
  'GEOPLASTYK', //OK
  'GERMANOFIL', //OK
  'GORSZYCIEL', //OK 2x
  'GRABIESTWO', //OK
  'GRANULOCYT', //OK
  'GROMNICZKA', //OK
  'GRUBASKIEM', //OK 2x
  'GRYPSUJCIE', //OK 2x
  'GRZECHOTKA', //OK
  'GRZYBOWSKI', //OK
  'GUZDRALSKI', //OK
  'GWIAZDOREK', //OK 2x
  'HAMOWNICZY', //OK
  'HANDLOWIEC', //OK
  'HEBRAJCZYK', //OK 2x
  'HIPNOTYZER', //OK
  'HIPOKRYZJA', //OK
  'HISTORYJKA', //OK 2x
  'HYDRONETKA', //OK
  'IMPOTENCJA', //OK
  'IMPULSATOR', //OK
  'INFORMATYK', //OK 2x
  'INSTRUKCJA', //OK
  'INSUREKCJA', //OK
  'INWESTYCJA', //OK
  'IZOCYJANEK', //OK
  'KANGURZYCO', //OK 2x
  'KASTRUJCIE', //OK 2x
  'KASZMIROWY', //OK
  'KATOLICYZM', //OK
  'KLASZTORNY', //OK
  'KLUCHOWATY', //OK
  'KONSUMPCJA', //OK 2x
  'KONSZACHTY', //OK
  'KRUCJATOWE', //OK
  'KUCHMISTRZ', //OK
  'KURIOZALNY', //OK
  'KWADRYLION', //OK 2x
  'LICHTARZYK', //OK
  'LICZYKRUPA', //OK 2x
  'LUTOWNICZY', //OK
  'MAGNETOWID', //OK 2x
  'MANUSKRYPT', //OK
  'MARSZOBIEG', //OK 2x
  'MASZTOWIEC', //OK
  'MELDUNKOWY', //OK
  'MIASTECZKO', //OK
  'MIZERUCHNY', //OK
  'MODELARSKI', //OK
  'MODERNISTA', //OK
  'MORDZIASTY', //OK 2x
  'MRUKLIWSZY', //OK
  'MUSZKIETON', //OK
  'NADGORLIWY', //OK
  'NAJCHUDSZY', //OK
  'NAJGRUBSZY', //OK
  'NEUROBLAST', //OK
  'NIEBURACKO', //OK 2x
  'NIEDBALUCH', //OK
  'NIEMCZYSKO', //OK 2x
  'NIERUCHAWY', //OK
  'NIEURODZAJ', //OK
  'OBRACHUNEK', //OK
  'OBSTRUKCJA', //OK
  'ODPISYWACZ', //OK 2x
  'OKRYJBIEDA', //OK 2x
  'OPUCHLIZNA', //OK
  'OSZUKANIEC', //OK 2x
  'PALOWNICZY', //OK 2x
  'PANCERZOWY', //OK
  'PANTURKIZM', //OK
  'PARKINGOWY', //OK 2x
  'PARSZYWIEC', //OK 2x
  'PARWENIUSZ', //OK
  'PASIBRZUCH', //OK 2x
  'PASKUDZTWO', //OK 2x
  'PATRYCJUSZ', //OK 2x
  'PIERWOUSTY', //OK
  'PIJACZYSKO', //OK 2x
  'PIOSENKARZ', //OK 2x
  'PIOSNECZKA', //OK
  'PISTACJOWY', //OK
  'PLASTIKOWY', //OK
  'PLUWIOGRAF', //OK 2x
  'PNIACZYSKO', //OK
  'PODBIERACZ', //OK 2x
  'PODEJRZANY', //OK 2x
  'PODGATUNEK', //OK
  'PODGRZYBEK', //OK 2x
  'PODSIEWACZ', //OK
  'PODSUFITKA', //OK
  'PODWIESZKA', //OK
  'POGARDLIWY', //OK
  'POGRANICZE', //OK
  'POKERZYSTA', //OK 2x
  'POLIURETAN', //OK
  'PORACHUNEK', //OK 2x
  'POSTKUBIZM', //OK
  'POWSTANIEC', //OK
  'PRAWNUCZEK', //OK 2x
  'PRODZIEKAN', //OK
  'PROSCENIUM', //OK
  'PROSTACZEK', //OK 2x
  'PRZEBOGATY', //OK 2x
  'PRZEBUDOWA', //OK
  'PRZEMYTNIK', //OK 2x
  'PRZESUWNIK', //OK
  'PRZEWODNIK', //OK
  'PRZYJACIEL', //OK 2x
  'PRZYSTANEK', //OK
  'PSEUDOBANK', //OK 2x
  'PSYCHOMETR', //OK
  'PUBLIKATOR', //OK
  'PUNKTOWIEC', //OK
  'PUZONISTKA', //OK
  'RATOWNICZY', //OK
  'REKWIZYCJA', //OK
  'RELATYWIZM', //OK 2x
  'RODEZYJSKI', //OK
  'ROTACYJNIE', //OK
  'ROZPUSTNIK', //OK 2x
  'RUMIANKOWY', //OK
  'RUSZNICOWY', //OK
  'SAMOJEZDNY', //OK
  'SAMORZUTNY', //OK
  'SAMOTNICZY', //OK
  'SANECZKOWY', //OK
  'SCHIZMATYK', //OK
  'SOCREALIZM', //OK 2x
  'SOLIDARUCH', //OK 2x
  'SPADKOWICZ', //OK 2x
  'SPELUNKOWY', //OK
  'SPRAWCZYNI', //OK
  'SPRZEDAJNY', //OK 2x
  'STEROWNICA', //OK
  'STRUMYCZEK', //OK
  'STRZELNICA', //OK 2x
  'STUDENCIAK', //OK
  'STUDZIENKA', //OK
  'STYPENDIUM', //OK
  'SUPERGLINA', //OK 2x
  'SUPERMOCNY', //OK 2x
  'SUPERTAJNY', //OK 2x
  'SUPERWIZJA', //OK 2x
  'SZABROWNIK', //OK 2x
  'SZLACHETNY', //OK 2x
  'SZMUGLERKA', //OK 2x
  'SZPIEGOMAN', //OK 2x
  'SZTABOWIEC', //OK 2x
  'SZTORMLINA', //OK
  'SZUBRAWIEC', //OK 2x
  'SZYBCIOREM', //OK 2x
  'SZYBERDACH', //OK
  'TAJEMNICZY', //OK 2x
  'TAKSOMIERZ', //OK
  'TARCZOWNIK', //OK
  'TECHNOKLUB', //OK 2x
  'TERMOKLINA', //OK
  'TERMOWIZJA', //OK 2x
  'TOPINAMBUR', //OK
  'TOWARZYSKI', //OK
  'TRAWNICZEK', //OK
  'TRIUMFALNY', //OK
  'TROPIKALNY', //OK
  'UDEPTYWACZ', //OK 2x
  'UPADOMIERZ', //OK 2x
  'UTRZYMANEK', //OK 2x
  'VOLKSWAGEN', //OK 2x
  'WACHMISTRZ', //OK
  'WESOLUCHNY', //OK 2x
  'WICEKONSUL', //OK
  'WIELGACHNY', //OK 2x
  'WIELKOUCHY', //OK
  'WINDYKATOR', //OK 2x
  'WODZIREJKA', //OK 2x
  'WULGARNIEJ', //OK
  'WYGODNICKA', //OK
  'WYKPIGROSZ', //OK 2x
  'WYRZUTNICA', //OK
  'ZACIERKOWY', //OK
  'ZASKRONIEC', //OK 2x
  'ZBIERACTWO', //OK 2x
  'ZIELARSTWO', //OK 2x
  'ZIELONKAWY', //OK
];

export const WORDS10UNIQUE_ALL_PL = [
  'ABRUZYJSKI',
  'ABSOLUTYZM',
  'ADENOWIRUS',
  'AGENTUROWY',
  'AGROBIZNES', //OK
  'AGROCHEMIK', //OK
  'AHISTORYZM',
  'AKCESORIUM',
  'AKTYNOWIEC',
  'ALBUMINOWY',
  'ALEMBIKOWY',
  'ALERGICZNY',
  'ALGIERCZYK',
  'ALKIERZOWY',
  'ALOFIJCZYK',
  'AMBICJONER',
  'AMBIENTOWY',
  'AMBIWERTYK',
  'AMORFICZNY',
  'AMPLITUNER', //OK
  'ANEGDOTYZM',
  'ANGIELCZYK',
  'ANTERYDIUM',
  'ANTWERPSKI',
  'ANTYLOGIZM',
  'ANTYLUDZKI',
  'ANTYPOLSKI', //OK
  'APHELICZNY',
  'APOCENTRUM',
  'ARCYBISKUP', //OK
  'ARGUMENCIK',
  'ARLEKINOWY',
  'ARTEZYJSKI',
  'ASTROFIZYK', //OK
  'ATMOSFERYK',
  'ATROFICZNY',
  'AUDYTORSKI',
  'BAJEROWSKI',
  'BAKELITOWY',
  'BANGIJCZYK',
  'BANKIETOWY',
  'BANKRUCTWO', //OK
  'BARCZEWSKI',
  'BARTODZIEJ', //OK
  'BAYEROWSKI',
  'BAZYLEJSKI',
  'BECZKOWATY',
  'BEDNARSTWO',
  'BEHAPOWSKI',
  'BEJRUTCZYK',
  'BELGRADZKI',
  'BERGSONIZM',
  'BEZCHMURNY', //OK
  'BEZGIPSOWY',
  'BEZISKROWY',
  'BEZKASTOWY',
  'BEZKLASOWY',
  'BEZKRWISTY',
  'BEZLITOSNY', //OK
  'BEZMULISTY',
  'BEZPALCOWY',
  'BEZPLANOWY',
  'BEZSMAKOWY',
  'BEZSMAROWY',
  'BEZSTANOWY',
  'BIMETALOWY',
  'BIODRZASTY',
  'BIOMETRYKA', //OK
  'BIOSYNTEZA',
  'BLIZNOWATY',
  'BOHATERSKI', //OK
  'BOHEMISTKA',
  'BOJADELSKI',
  'BOLIMUSZKA',
  'BRAJLOWSKI',
  'BRANDZLOWY',
  'BREAKPOINT',
  'BRUTALNIEJ', //OK
  'BRUZDOWATY',
  'BRZYDACTWO', //OK
  'BUDOWNICZY', //OK
  'BUKOLICZNY',
  'BUNKROWATY',
  'BUNKROWIEC',
  'BURACZKOWY',
  'BURACZYSKO', //OK
  'BURLESKOWY',
  'BURSZTYNEK', //OK
  'BURSZTYNKA',
  'BUTELCZYNA', //OK
  'BUTNIEJSZY',
  'BUTONIERKA',
  'BUZDYGANEK', //OK
  'CAMERLINGO',
  'CAMPINGOWY',
  'CARTINGOWY',
  'CARVINGOWY',
  'CASTINGOWY',
  'CEBULOWATY', //OK
  'CEGLARSTWO',
  'CELIBATOWY',
  'CEMBROWINA',
  'CENOBITYZM',
  'CENTRALIZM',
  'CENTRYFUGA',
  'CENTYFOLIA',
  'CERAMIDOWY',
  'CERANOWSKI',
  'CEZARYJSKI',
  'CHABROLIZM',
  'CHALDEJSKI',
  'CHAMBERTIN',
  'CHANTYJSKI',
  'CHARLESTON',
  'CHARTUMSKI',
  'CHEMIZATOR',
  'CHEMOTYPIA',
  'CHIROPLAST',
  'CHMURZYSKO',
  'CHODLIWSZY',
  'CHOLEWKARZ',
  'CHORZELSKI',
  'CHRUSTNIAK',
  'CHUDERLAWY',
  'CHWIERUTNY',
  'CIEMNORUDY',
  'CISURANOWY',
  'CMENTARZYK', //OK
  'CNOTLIWSZY',
  'CORNFLAKES',
  'CORNFLEKSY',
  'CUDNIEJSZY',
  'CUKRODAJNY',
  'CUMBERLAND',
  'CURLINGOWY',
  'CYRENAJSKI',
  'CYTOKINEZA',
  'CZAROWNIEJ',
  'CZARTOWSKI',
  'CZEMPIONAT',
  'CZEMPIONKA',
  'CZERNIDLAK',
  'CZERPAKOWY',
  'CZERWONIAK',
  'CZESANKOWY',
  'CZIMURENGA',
  'CZUJNIKOWY',
  'CZYSTODRUK',
  'DAGLEZJOWY',
  'DAHOMEJSKI',
  'DALESZYCKI',
  'DAWKOMIERZ',
  'DAWNIEJSZY',
  'DEBILOWATY', //OK
  'DEKLINATOR',
  'DEKSTRALNY',
  'DELATORSKI',
  'DELHIJCZYK',
  'DEMIURGOWY',
  'DEMULGATOR',
  'DEPUTOWANY',
  'DEPUTOWANY', //OK
  'DESKRYPCJA',
  'DESTRUKCJA', //OK
  'DESZYFRANT', //OK
  'DETALICZNY',
  'DIABELSTWO',
  'DIAGNOSTYK',
  'DIALEKTOWY',
  'DIALEKTYZM',
  'DIAMENTOWY',
  'DNIESTROWY',
  'DOBIERALNY',
  'DOKUCZLIWY', //OK
  'DOMPTEURKA',
  'DOPISYWACZ',
  'DOTKLIWSZY',
  'DOTLENIACZ',
  'DOWCIPASEK', //OK
  'DOWIETRZNY',
  'DOZYMETRIA',
  'DRABINKOWY',
  'DRAPIESTWO',
  'DRELICHOWY',
  'DREPANOCYT',
  'DRUMLINOWY',
  'DRUTOWNICA', //OK
  'DRYLOWNICA',
  'DRZEWIASTY',
  'DRZEWOSTAN', //OK
  'DUBLERSTWO',
  'DUFNIEJSZY',
  'DUMNIEJSZY',
  'DUMPINGOWY',
  'DUPLEKSOWY',
  'DUPNEGATYW', //OK
  'DUPNIEJSZY',
  'DURALEXOWY',
  'DURNIEJSZY',
  'DUSZNICOWY',
  'DWUBOISTKA',
  'DWUCHLOREK', //OK
  'DWUMOCZNIK',
  'DWUSIECZNA',
  'DWUSIECZNY',
  'DYKCJONARZ',
  'DYLETANCKI',
  'DYSFUNKCJA', //OK
  'DYSTROFIZM',
  'DYSZOWNICA',
  'DYWIZJONER',
  'DZIUPLASTY',
  'DZWONIASTY',
  'EDYFIKATOR',
  'EDYNBURSKI',
  'EGZORCYSTA', //OK
  'EKSDYWIZJA',
  'EKSPOZYCJA',
  'ELIPSOGRAF',
  'ELIPSOWATY',
  'EMHADOWSKI',
  'EMPIRYCZKA',
  'EMPIRYSTKA',
  'EPIZODYSTA',
  'ESTRADKOWY',
  'EUFORYCZKA',
  'EUPATRYDZI',
  'EURYTOPIZM',
  'FARTOWNIEJ',
  'FARTUCHOWY',
  'FARYZEJSKI',
  'FECHMISTRZ', //OK
  'FIRLEJCZYK',
  'FLADROWNIK',
  'FLASZOWIEC',
  'FLORECISTA',
  'FLUKSOMETR',
  'FLUWIOMETR',
  'FOLWARCZEK',
  'FOLWARCZNY',
  'FONETYCZKA',
  'FORKASZTEL',
  'FORMALNIEJ',
  'FORTALESKI',
  'FRAGMENCIK', //OK
  'FRAMPOLSKI',
  'FRANTOWSKI',
  'FRASOBLIWY',
  'FREBLOWSKI',
  'FREUDOWSKI',
  'FREUDYSTKA',
  'FRONDYSTKA',
  'FRONTALIZM',
  'FRYSZTACKI', //OK
  'FRYTOWANIE',
  'FRYWOLITEK',
  'FRYWOLITKA',
  'FRYWOLNIEJ',
  'FTALEINOWY',
  'FURGONETKA', //OK
  'FURGOTLIWY',
  'FURKOTLIWY',
  'FUZJONISTA', //OK
  'GABINETOWY',
  'GALENITOWY',
  'GALERNICZY',
  'GALERYSTOM',
  'GARBNIKOWY',
  'GAWORZYCKI',
  'GBURLIWSZY',
  'GDERLIWSZY',
  'GEOPLASTYK', //OK
  'GERMANOFIL', //OK
  'GERMINACJO',
  'GILOTYNUJE',
  'GIRLANDOWY',
  'GLAUBERSKI',
  'GLAUKOFITY',
  'GLINOKRZEM',
  'GNIAZDKOWY',
  'GNOSTYCZKA',
  'GODNIEJSZY',
  'GOLCZEWSKI',
  'GOLDWYNIZM',
  'GORSZYCIEL', //OK
  'GORZEKWIAT',
  'GOTLANDZKI',
  'GRABIESTWO', //OK
  'GRABNOWSKI',
  'GRADKOLICE',
  'GRANULOCYT', //OK
  'GROMADECKI',
  'GROMNICZKA', //OK
  'GRUBASKIEM', //OK
  'GRUDKOWATY',
  'GRUDKOWNIA',
  'GRUJECZNIK',
  'GRYPSOWALI',
  'GRYPSUJCIE', //OK
  'GRZBIETOWY',
  'GRZECHOTKA', //OK
  'GRZYBOWSKI', //OK
  'GUSTOWNIEJ',
  'GUZDRALSKI', //OK
  'GUZIKOWATY',
  'GWARDYJSKI',
  'GWIAZDOREK', //OK
  'GYMNOBLAST',
  'GYNODIECJA',
  'HACKERSTWO',
  'HAMBURCZYK',
  'HAMOWNICZY', //OK
  'HANDLOWIEC', //OK
  'HANOWERSKI',
  'HARLEMCZYK',
  'HEBRAJCZYK', //OK
  'HEDONISTKA',
  'HEKSAPLOID',
  'HELMINTOZA',
  'HEMOLIZYNA',
  'HIPEASTRUM',
  'HIPEROKSJA',
  'HIPNOTYZER', //OK
  'HIPOKRYZJA', //OK
  'HIPOTECZNY',
  'HIPOTENSJA',
  'HISTORYJKA', //OK
  'HOMILETYKA',
  'HONDURASKI',
  'HONIARCZYK',
  'HOTELARSKI',
  'HUMORYSTKA',
  'HUMORZASTY',
  'HYDROLIMFA',
  'HYDROLIZAT',
  'HYDRONETKA', //OK
  'ILUMETROWY',
  'IMPETYCZKA',
  'IMPOTENCJA', //OK
  'IMPULSATOR', //OK
  'INCROYABLE',
  'INFORMATYK', //OK
  'INOCERAMUS',
  'INSKRYPCJA',
  'INSPEKTOWY',
  'INSTRUKCJA', //OK
  'INSUREKCJA', //OK
  'INWESTORKA',
  'INWESTYCJA', //OK
  'IZOBUTYLEN',
  'IZOCYJANEK', //OK
  'IZOLEUCYNA',
  'JABLONECKI',
  'JADOWITSZY',
  'JARCZOWSKI',
  'JARZENIOWY',
  'JASKROWIEC',
  'JASNOBREWY',
  'JAZGOTLIWY',
  'JEDNOZWITY',
  'JEDWABISTY',
  'JEDYNACTWO',
  'JERYCHONKA',
  'JUMPSALING',
  'JUSTIZMORD',
  'JUTLANDZKI',
  'JUTRZNIOWY',
  'KABOTYNIZM',
  'KAJEPUTOWY',
  'KALENICOWY',
  'KALETNICZY',
  'KALISTEMON',
  'KAMPESZOWY',
  'KANGURZYCO', //OK
  'KANISTROWY',
  'KARNIEJSZY',
  'KARTINGOWY',
  'KARTUSZOWY',
  'KARUZELOWY',
  'KASTINGOWY',
  'KASTRUJCIE', //OK
  'KASZMIROWY', //OK
  'KASZTELOWY',
  'KATOLICYZM', //OK
  'KEMPINGOWY',
  'KENOTAFIUM',
  'KINETOGRAF',
  'KINETOGRAM',
  'KLAJSTROWY',
  'KLARNETOWY',
  'KLAROWNIEJ',
  'KLASTEROWY',
  'KLASZTORNY', //OK
  'KLISZOGRAF',
  'KLISZOGRAM',
  'KLIWERSZOT',
  'KLOSTERIUM',
  'KLUCHOWATY', //OK
  'KNIDOBLAST',
  'KOLENCHYMA',
  'KOMPETYCJA',
  'KONCEPTYZM',
  'KONSUMPCJA', //OK
  'KONSYLIARZ',
  'KONSZACHTY', //OK
  'KOPERNICJA',
  'KORNECISTA',
  'KORNIEJSZY',
  'KORZENISTY',
  'KRASNOLICY',
  'KREWNIACZY',
  'KROCHMALNY',
  'KROSTAWIEC',
  'KRUCJATOWE', //OK
  'KRUPCZASTY',
  'KRYSTALOID',
  'KRZEWIASTY',
  'KRZEWOSTAN',
  'KSANTOFILE',
  'KSEROFILNY',
  'KUCHARSTWO',
  'KUCHMISTRZ', //OK
  'KUGLARSTWO',
  'KUGLERSTWO',
  'KULOMETRIA',
  'KUMBERLAND',
  'KUNDLOWATY',
  'KUPLECISTA',
  'KUPLERSTWO',
  'KURDESZOWY',
  'KURIOZALNY', //OK
  'KURZENIOWY',
  'KUSZNICTWO',
  'KWADRUPLET',
  'KWADRYLION', //OK
  'KWASOLUBNY',
  'KWASOMIERZ',
  'LANDSZTURM',
  'LASECZKOWY',
  'LASTRIKOWY',
  'LEASINGOWY',
  'LEDZIUCHNY',
  'LEKCJONARZ',
  'LEMUROWATY',
  'LETNISKOWY',
  'LICHTARZYK', //OK
  'LICZYKRUPA', //OK
  'LIGUSTROWY',
  'LIPOSUKCJA',
  'LITERAKOWY',
  'LOMBARDZKI',
  'LOTNIEJSZY',
  'LUCERNISKO',
  'LUDNIEJSZY',
  'LUKRECJOWY',
  'LUKSOMIERZ',
  'LUNOCHEMIA',
  'LUSTERKOWY',
  'LUTERANIZM',
  'LUTOWNICZY', //OK
  'MACHERSTWO',
  'MACIEJKOWY',
  'MACIERZOWY',
  'MACKINTOSH',
  'MADERYJSKI',
  'MAGHREBSKI',
  'MAGNETOWID', //OK
  'MAGNEZJOWY',
  'MAKLERSTWO',
  'MALBORCZYK',
  'MALEZYJSKI',
  'MALOWNICZY',
  'MALUTECZKI',
  'MANDEJCZYK',
  'MANGROWIEC',
  'MANKIETOWY',
  'MANUSKRYPT', //OK
  'MARBLITOWY',
  'MARCHEWNIK',
  'MARCINKOWY',
  'MARKOTNIEJ',
  'MARNIEJSZY',
  'MARSYLIOWE',
  'MARSZOBIEG', //OK
  'MARZENIOWY',
  'MASZTOWIEC', //OK
  'MATECZKOWY',
  'MEBLARSTWO',
  'MEGARYJSKI',
  'MELAFIROWY',
  'MELDUNKOWY', //OK
  'MELODYSTKA',
  'MESZKOWATY',
  'METALICZNY',
  'METKOWNICA',
  'METODYCZKA',
  'MIASTECZKO', //OK
  'MIECHOWATY',
  'MIECZOWATY',
  'MIESZAKOWY',
  'MIESZKALNY',
  'MIKROCEFAL',
  'MIKROCYSTA',
  'MILANEZOWY',
  'MINARETOWY',
  'MINCARSTWO',
  'MINCERSTWO',
  'MINUTECZKA',
  'MIZERACTWO',
  'MIZERUCHNY', //OK
  'MLECZANOWY',
  'MLECZARSKI',
  'MLEKODAJNY',
  'MOCNIEJSZY',
  'MODELARSKI', //OK
  'MODERNISTA', //OK
  'MODLITEWNY',
  'MODNIEJSZY',
  'MODRZEWINA',
  'MODRZEWNIK',
  'MODRZYNIEC',
  'MOHYLEWSKI',
  'MOLIERYSTA',
  'MORDZIASTY', //OK
  'MOTYLICZKA',
  'MOWNIEJSZY',
  'MRUKLIWSZY', //OK
  'MRZECHLINA',
  'MSZYCOWATE',
  'MUCHOTRZEW',
  'MUNDIALOWY',
  'MURANOWSKI',
  'MURENOWATY',
  'MUROWANIEC',
  'MUSICALOWY',
  'MUSZELKOWY',
  'MUSZKATOWY',
  'MUSZKIETON', //OK
  'MUSZLOWATY',
  'MUSZLOWIEC',
  'MUZYKOGRAF',
  'MYDLARSTWO',
  'NADBITKOWY',
  'NADGORLIWY', //OK
  'NADKOMPLET',
  'NADMUCHOWY',
  'NADOLBRZYM',
  'NADREGLOWY',
  'NAGIETKOWY',
  'NAJBIELSZY',
  'NAJBLEDSZY',
  'NAJCHUDSZY', //OK
  'NAJGRUBSZY', //OK
  'NAJLICHSZY',
  'NEGATYWIZM',
  'NEOSLAWIZM',
  'NEUROBLAST', //OK
  'NEUSTADZKI',
  'NEUTRALIZM',
  'NIAMEJCZYK',
  'NIEBURACKO', //OK
  'NIECKOWATY',
  'NIEDBALUCH', //OK
  'NIEMCZYSKO', //OK
  'NIEODPARTY',
  'NIERUCHAWY', //OK
  'NIEURODZAJ', //OK
  'NORWIDYSTA',
  'NOWELISTKA',
  'NUWORYSZKA',
  'OBRACHUNEK', //OK
  'OBSKURNIEJ',
  'OBSTALUNEK',
  'OBSTRUKCJA', //OK
  'OBUSIECZNY',
  'ODBURKLIWY',
  'ODCZUWALNY',
  'ODLEWNICZY',
  'ODPISYWACZ', //OK
  'ODTLENIACZ',
  'ODWIETRZNY',
  'ODZYSKNICA',
  'OFICERZYNA',
  'OGRZEWALNY',
  'OGRZEWNICA',
  'OKRYJBIEDA', //OK
  'OLDENBURKA',
  'OLEJNICZKA',
  'OLSZANECKI',
  'OLSZTYNIAK',
  'ONEGDAJSZY',
  'ONTARYJSKI',
  'OPARZELNIK',
  'OPUCHLIZNA', //OK
  'ORGANICYZM',
  'OSTENDCZYK',
  'OSZUKANIEC', //OK
  'OUTSIDERKA',
  'PACIERZOWY',
  'PALICZKOWY',
  'PALMETKOWY',
  'PALOWNICZY', //OK
  'PALUSZKOWY',
  'PAMFLETOWY',
  'PANCERZOWY', //OK
  'PANEGIRYZM',
  'PANEROTYZM',
  'PANIBERYZM',
  'PANTURECKI',
  'PANTURKIZM', //OK
  'PARCHOWSKI',
  'PARCZEWSKI',
  'PARKIETOWY',
  'PARKINGOWY', //OK
  'PARNIEJSZY',
  'PARSZYWIEC', //OK
  'PARSZYWIEJ',
  'PARUDNIOWY',
  'PARWENIUSZ', //OK
  'PASIBRZUCH', //OK
  'PASIERBOWY',
  'PASKUDNIEJ',
  'PASKUDZTWO', //OK
  'PATHFINDER',
  'PATRYCJUSZ', //OK
  'PAZURKOWCE',
  'PELAGICZNY',
  'PELIKANOWY',
  'PELIKOZAUR',
  'PERUCZKOWY',
  'PETYHORSKI',
  'PIEKARSTWO',
  'PIELUCHOWY',
  'PIERWOUSTY', //OK
  'PIETRUSZKA',
  'PIEZOKWARC',
  'PIGMENTOWY',
  'PIJACZYSKO', //OK
  'PILASTROWY',
  'PILCHOWATE',
  'PILCHOWATY',
  'PILOREKCJA',
  'PINEALOCYT',
  'PIOSENKARZ', //OK
  'PIOSNECZKA', //OK
  'PIRYDOKSAL',
  'PISTACJOWY', //OK
  'PLASTIKOWY', //OK
  'PLATYNOWCE',
  'PLECHOWATY',
  'PLEMNIKOWY',
  'PLUJKOWATE',
  'PLUJKOWATY',
  'PLUWIOGRAF', //OK
  'PLUWIOGRAM',
  'PLUWIOMETR',
  'PNEUMOGRAF',
  'PNEUMOLIZA',
  'PNIACZYSKO', //OK
  'POCHUTLIWY',
  'POCHWIASTY',
  'POCZDAMSKI',
  'PODATNICZY',
  'PODBIERACZ', //OK
  'PODCASTING',
  'PODCHMURNY',
  'PODEJRZANY',
  'PODEJRZANY', //OK
  'PODESZWICA',
  'PODGATUNEK', //OK
  'PODGRZYBEK', //OK
  'PODHAJECKI',
  'PODKRAJCZY',
  'PODSIEWACZ', //OK
  'PODSTAWNIK',
  'PODSTYCZNA',
  'PODSUFITKA', //OK
  'PODSUWNICA',
  'PODTRZYMKA',
  'PODULICZNY',
  'PODURALSKI',
  'PODWIESZKA', //OK
  'POGARDLIWY', //OK
  'POGRANICZE', //OK
  'POHUTNICZY',
  'POKERZYSTA', //OK
  'POKRZYWIEC',
  'POKUTNICZY',
  'POLEMICZNY',
  'POLEMISTKA',
  'POLESZUCKI',
  'POLISTYREN',
  'POLIURETAN', //OK
  'POMNIEJSZY',
  'PORACHUNEK', //OK
  'PORADNICZY',
  'POSTKUBIZM', //OK
  'POWIETRZNY',
  'POWSTANIEC', //OK
  'POWSZECHNY',
  'PRALNICTWO',
  'PRAWIECZNY',
  'PRAWNUCZEK', //OK
  'PREFIKSOWY',
  'PREJUDYKAT',
  'PRELUDIOWY',
  'PRODZIEKAN', //OK
  'PROFETYCKI',
  'PROGNATYZM',
  'PROSCENIUM', //OK
  'PROSEKUCJA',
  'PROSIACZEK',
  'PROSKYNEZA',
  'PROSTACZEK', //OK
  'PROSZALNIK',
  'PRUDONISTA',
  'PRYMICJANT',
  'PRYWATNIEJ',
  'PRYZMATOID',
  'PRZEBOGATY', //OK
  'PRZEBUDOWA', //OK
  'PRZECHODNI',
  'PRZECIWJAD',
  'PRZEDBITKA',
  'PRZEDNUTKA',
  'PRZEGUBOWY',
  'PRZELOTNIA',
  'PRZEMYTNIK', //OK
  'PRZEOBFITY',
  'PRZESMUTNY',
  'PRZESMYCKI',
  'PRZESTAWNY',
  'PRZESUWNIK', //OK
  'PRZEWODNIK',
  'PRZEWODNIK', //OK
  'PRZYBUDOWA',
  'PRZYCHODNE',
  'PRZYCHODNI',
  'PRZYJACIEL', //OK
  'PRZYLISTEK',
  'PRZYSIONEK',
  'PRZYSTANEK', //OK
  'PRZYTULICA',
  'PRZYWIANEK',
  'PSALMICZNY',
  'PSALTERION',
  'PSALTERIUM',
  'PSEUDOBANK', //OK
  'PSYCHOGRAF',
  'PSYCHOGRAM',
  'PSYCHOLEKT',
  'PSYCHOMETR', //OK
  'PSYCHROFIT',
  'PTASZYNIEC',
  'PUBLICYSTA',
  'PUBLIKATOR', //OK
  'PUCHLINOWY',
  'PUENTYLIZM',
  'PUKLOWANIE',
  'PULSOMIERZ',
  'PUNKTOWIEC', //OK
  'PURYTANIZM',
  'PUSTELNICA',
  'PUSZKOWATY',
  'PUZONISTKA', //OK
  'RACHUNKOWY',
  'RADOSZYCKI',
  'RALOKSIFEN',
  'RAPTOWNIEJ',
  'RATOWNICZY', //OK
  'RECHOTLIWY',
  'RECITALOWY',
  'REKOGNICJA',
  'REKWIZYCJA', //OK
  'RELATYWIZM', //OK
  'RIKETSJOZA',
  'RODEZYJSKI', //OK
  'ROHATYNIEC',
  'ROHATYNIEC',
  'ROSPLENICA',
  'ROTACYJNIE', //OK
  'ROZBIEGANY',
  'ROZPESTLIN',
  'ROZPLENICA',
  'ROZPUSTNIK', //OK
  'ROZSUWALNY',
  'ROZWALISTY',
  'ROZWIJALNY',
  'RUANDYJSKI',
  'RUBASZNIEJ',
  'RUCHLIWSZY',
  'RUMIANKOWY', //OK
  'RUSZNICOWY', //OK
  'RUSZTOWINA',
  'RWANDYJSKI',
  'RYCHTALSKI',
  'RYCHWALSKI',
  'RYMANOWSKI',
  'RZUTKOWIEC',
  'SADOWNICZY',
  'SADZENIOWY',
  'SAMOCZEPNY',
  'SAMOJEDZKI',
  'SAMOJEZDNY', //OK
  'SAMORZUTNY', //OK
  'SAMOTNICZY', //OK
  'SAMOTRZECI',
  'SAMOWIEDNY',
  'SAMOZGUBNY',
  'SANECZKOWY', //OK
  'SCALENIOWY',
  'SCHERZANDO',
  'SCHIZMATYK', //OK
  'SCHLAGWORT',
  'SCHLUDNIEJ',
  'SCYNKOWATE',
  'SEPTARIOWY',
  'SEPTYLIARD',
  'SERAFICZNY',
  'SIARCZKOWY',
  'SIELANKOWY',
  'SIERPOWATY',
  'SKALENIOWY',
  'SKANDOWIEC',
  'SKARBOWIEC',
  'SKLEROCJUM',
  'SKRZEPLINA',
  'SKRZYDLICA',
  'SKRZYDLINA',
  'SKRZYPOWCE',
  'SKUMBRIOWY',
  'SMARTPHONE',
  'SOCREALIZM', //OK
  'SOLIDARUCH', //OK
  'SOLIDARYZM',
  'SOUNDTRACK',
  'SPADKOWICZ', //OK
  'SPADOMIERZ',
  'SPALENIOWY',
  'SPARDEKOWY',
  'SPARINGOWY',
  'SPEDYTORKA',
  'SPEKTRALNY',
  'SPELUNKOWY', //OK
  'SPICHRZOWY',
  'SPORANGIUM',
  'SPRAWCZYNI', //OK
  'SPRAYOWIEC',
  'SPRZEDAJNY', //OK
  'SPUTNIKOWY',
  'STEFANKOWY',
  'STERNICZKA',
  'STEROWALNY',
  'STEROWNICA', //OK
  'STILBENOWY',
  'STOLNICZKA',
  'STRACHLIWY',
  'STROFICZNY',
  'STRONICZKA',
  'STRUMYCZEK', //OK
  'STRUNOWIEC',
  'STRZELNICA', //OK
  'STRZYGONIA',
  'STUDENCIAK', //OK
  'STUDZIENKA', //OK
  'STUGRAMOWY',
  'STUMARKOWY',
  'STYPENDIUM', //OK
  'SUBLIMATOR',
  'SUBPOLARNY',
  'SUCHODRZEW',
  'SUCHOKWIAT',
  'SULFONAMID',
  'SUMIKOWATE',
  'SUMIKOWATY',
  'SUPERGLINA', //OK
  'SUPERLATYW',
  'SUPERMACHO',
  'SUPERMOCNY', //OK
  'SUPERMODNY',
  'SUPERTAJNY', //OK
  'SUPERWIZJA', //OK
  'SURFINGOWY',
  'SURMIOWATE',
  'SURMIOWATY',
  'SYLABOWIEC',
  'SYMILOGRAF',
  'SYMPLACTWO',
  'SYNCHROMIA',
  'SYNEKDOCHA',
  'SZABROWNIK', //OK
  'SZACUNKOWY',
  'SZALUNKOWY',
  'SZKAFUTOWY',
  'SZLACHETNY', //OK
  'SZLAMOWNIK',
  'SZLOCHANIE',
  'SZMERGLOWY',
  'SZMIROWATY',
  'SZMUGLERKA', //OK
  'SZNUROWATY',
  'SZPACHLOWY',
  'SZPALERNIK',
  'SZPALEROWY',
  'SZPERACTWO',
  'SZPICOWATY',
  'SZPIEGOMAN', //OK
  'SZPINETOWY',
  'SZTABOWIEC', //OK
  'SZTAGOWNIK',
  'SZTALUGOWY',
  'SZTORMLINA', //OK
  'SZUBRAWIEC', //OK
  'SZUFLADOWY',
  'SZUPINKOWY',
  'SZYBCIOREM', //OK
  'SZYBERDACH', //OK
  'SZYFONIERA',
  'SZYKOWNIEJ',
  'TAJEMNICZY', //OK
  'TAKSOMIERZ', //OK
  'TAMOKSIFEN',
  'TANGERCZYK',
  'TARCZOWNIK', //OK
  'TARLISKOWY',
  'TASIEMCOWY',
  'TASIEMKOWY',
  'TECHNOGRAM',
  'TECHNOKLUB', //OK
  'TEMPORALNY',
  'TERMOFILNY',
  'TERMOKLINA', //OK
  'TERMOWIZJA', //OK
  'TEURGICZNY',
  'THUNBERGIA',
  'TOPINAMBUR', //OK
  'TOWARZYSKI', //OK
  'TRAGEDIOWY',
  'TRAMPOWSKI',
  'TRAWNICZEK', //OK
  'TREKINGOWY',
  'TRIUMFALNY', //OK
  'TROPIKALNY', //OK
  'TRUFLOWIEC',
  'TRYBOWANIE',
  'TRYCHINOZA',
  'TRYSKAWIEC',
  'TRZEBIONKA',
  'TULIPANOWY',
  'TUNEZYJSKI',
  'TURNIEJOWY',
  'TYCZKOWINA',
  'TYRANICZEK',
  'UCHWYTNIEJ',
  'UDEPTOWINY',
  'UDEPTYWACZ', //OK
  'UGANDYJSKI',
  'UJAZDOWSKI',
  'ULJANOWSKI',
  'UPADOMIERZ', //OK
  'URBANOZIEM',
  'UROKLIWSZY',
  'USTAWICZNY',
  'USZAKOWIEC',
  'UTERODYNIA',
  'UTRZYMANEK', //OK
  'VOLKSWAGEN', //OK
  'WACHMISTRZ', //OK
  'WALEZYJSKI',
  'WALNIEJSZY',
  'WARCHOLSKI',
  'WARIOPLEKS',
  'WEIMARCZYK',
  'WERSALCZYK',
  'WESOLUCHNY', //OK
  'WICEKONSUL', //OK
  'WICHRZYSKO',
  'WIELGACHNY', //OK
  'WIELKOUCHY', //OK
  'WIELOUSTNY',
  'WIETRZYSKO',
  'WINDSKATER',
  'WINDYKATOR', //OK
  'WIRULENCJA',
  'WISCERALNY',
  'WIZJONERKA',
  'WKOLEJNICA',
  'WODZIREJKA', //OK
  'WOKALICZNY',
  'WOLNIEJSZY',
  'WOLUMETRIA',
  'WSTECZNIAK',
  'WSZELAKOBY',
  'WULGARNIEJ', //OK
  'WYGODNICKA', //OK
  'WYKPIGROSZ', //OK
  'WYKROJNICA',
  'WYKROPLINA',
  'WYRZUTNICA', //OK
  'WYSKROBINA',
  'WYSMUKLICA',
  'WYSMUKLICE',
  'ZABIERKOWY',
  'ZACIERKOWY', //OK
  'ZAKULISOWY',
  'ZAKWEFIONY',
  'ZAMBROWSKI',
  'ZASKRONIEC', //OK
  'ZAWROTNIEJ',
  'ZBESTWIONY',
  'ZBIERACTWO', //OK
  'ZBIERAKOWY',
  'ZEBRANIOWY',
  'ZESKROBINA',
  'ZIELARSTWO', //OK
  'ZIELONKAWY', //OK
  'ZIUDWESTKA',
  'ZLUMPOWANY',
  'ZNACHORSKI',
  'ZYSKOWNIEJ',
];
