export const WORDS_10LETTERSUNIQUE_COOL_EN = [
  'AFTERSHOCK', //OK
  'ALGORITHMS', //OK
  'AMPLITUDES', //OK
  'ARTICHOKES', //OK
  'BACKGROUND', //OK
  'BACKSLIDER', //OK
  'BANDOLIERS', //OK
  'BANKRUPTCY', //OK
  'BEACHFRONT', //OK
  'BENCHMARKS', //OK
  'BINOCULARS', //OK
  'BIRTHPLACE', //OK
  'BLACKSMITH', //OK
  'BLACKTHORN', //OK
  'BLUEPRINTS', //OK
  'BOUNDARIES', //OK
  'BREAKPOINT', //OK
  'BUTCHERING', //OK
  'CAMPGROUND', //OK
  'CHIVALROUS', //OK
  'CLIPBOARDS', //OK
  'CLOTHESPIN', //OK
  'COMBATHELP', //OK
  'COMPATIBLE', //OK
  'CORNFLAKES', //OK
  'CUMBERLAND', //OK
  'CYBERPUNKS', //OK
  'DEATHBLOWS', //OK
  'DEFOLIANTS', //OK
  'DEMOGRAPHY', //OK
  'DESTROYING', //OK
  'DUMBWAITER', //OK
  'DUPLICATOR', //OK
  'EXHAUSTION', //OK
  'FARSIGHTED', //OK
  'FLAMINGOES', //OK
  'GLAMOURIZE', //OK
  'GODFATHERS', //OK
  'GODPARENTS', //OK
  'GOLDBRICKS', //OK
  'HARLEQUINS', //OK
  'HARVESTING', //OK
  'HYDROPLANE', //OK
  'HYPNOTIZED', //OK
  'JOURNALIST', //OK
  'JUDGMENTAL', //OK
  'LADYFINGER', //OK
  'LOVEMAKING', //OK
  'LUMBERJACK', //OK
  'MACKINTOSH', //OK
  'MANUSCRIPT', //OK
  'MISFORTUNE', //OK
  'MONARCHIST', //OK
  'MOTHERLAND', //OK
  'NIGHTCLUBS', //OK
  'NIGHTMARES', //OK
  'PAINTBRUSH', //OK
  'PALINDROME', //OK
  'PATHFINDER', //OK
  'PLAYGROUND', //OK
  'PRECAUTION', //OK
  'PROSCENIUM', //OK
  'REGULATION', //OK
  'REPUBLICAN', //OK
  'SHOPLIFTER', //OK
  'SUPERWOMAN', //OK
  'TRAMPOLINE', //OK
  'ULTRASONIC', //OK
  'VIBRAPHONE', //OK
  'VOLKSWAGEN', //OK
];

export const WORDS10UNIQUE_ALL_PL = [
  'AFTERSHOCK', //OK
  'ALGORITHMS', //OK
  'AMPLITUDES', //OK
  'ARTICHOKES', //OK
  'BACKGROUND', //OK
  'BACKSLIDER', //OK
  'BANDOLIERS', //OK
  'BANKRUPTCY', //OK
  'BEACHFRONT', //OK
  'BENCHMARKS', //OK
  'BINOCULARS', //OK
  'BIRTHPLACE', //OK
  'BLACKSMITH', //OK
  'BLACKTHORN', //OK
  'BLOCKADING',
  'BLOCKHEADS',
  'BLUEPRINTS', //OK
  'BLUSTERING',
  'BOLSTERING',
  'BOULEVARDS',
  'BOUNDARIES', //OK
  'BOYFRIENDS',
  'BRACKETING',
  'BREAKDOWNS',
  'BREAKPOINT', //OK
  'BRUTALIZED',
  'BRUTALIZES',
  'BUTCHERING', //OK
  'BYPRODUCTS',
  'CAMPGROUND', //OK
  'CENTIGRAMS',
  'CHAIRWOMEN',
  'CHAMPIONED',
  'CHARMINGLY',
  'CHIVALROUS', //OK
  'CHLORINATE',
  'CLAMBERING',
  'CLAMPDOWNS',
  'CLIPBOARDS', //OK
  'CLOTHESPIN',
  'CLOTHESPIN', //OK
  'CLUSTERING',
  'COLUMBINES',
  'COMBATHELP', //OK
  'COMPATIBLE', //OK
  'COMPATIBLY',
  'COMPLAINED',
  'COMPLAINER',
  'COMPLAINTS',
  'COMPLETING',
  'COMPLEXITY',
  'COMPULSIVE',
  'CONFIGURED',
  'CONFIGURES',
  'CONFUSEDLY',
  'CONJUGATED',
  'CONJUGATES',
  'CONSUMABLE',
  'COPULATING',
  'COPYRIGHTS',
  'CORNFLAKES', //OK
  'CREDITABLY',
  'CREMATIONS',
  'CRUMBLIEST',
  'CRYSTALIZE',
  'CULMINATED',
  'CULMINATES',
  'CUMBERLAND', //OK
  'CURTSEYING',
  'CUSTOMIZED',
  'CYBERPUNKS', //OK
  'DAVENPORTS',
  'DEATHBLOWS', //OK
  'DEBAUCHING',
  'DEBONAIRLY',
  'DECATHLONS',
  'DECORATING',
  'DEFAULTING',
  'DEFOLIANTS', //OK
  'DEFROSTING',
  'DEMOGRAPHY', //OK
  'DEPILATORY',
  'DESOLATING',
  'DESPICABLY',
  'DESTROYING', //OK
  'DEXTROUSLY',
  'DISBARMENT',
  'DISCOURAGE',
  'DISGRUNTLE',
  'DISHARMONY',
  'DISPATCHER',
  'DISPUTABLE',
  'DOWNSTREAM',
  'DUMBWAITER',
  'DUMBWAITER', //OK
  'DUPLICATES',
  'DUPLICATOR', //OK
  'EARTHLINGS',
  'EDUCATIONS',
  'EMULATIONS',
  'EPISTOLARY',
  'EXACTINGLY',
  'EXHAUSTING',
  'EXHAUSTION', //OK
  'EXHUMATION',
  'FALTERINGS',
  'FARSIGHTED',
  'FARSIGHTED', //OK
  'FETCHINGLY',
  'FLAMINGOES',
  'FLAMINGOES', //OK
  'FLAVORINGS',
  'FLOURISHED',
  'FLUORIDATE',
  'FLUSTERING',
  'FLYWEIGHTS',
  'FORGIVABLE',
  'FORMALIZED',
  'FORMALIZES',
  'FORMIDABLE',
  'FORMIDABLY',
  'FORMULATED',
  'FORMULATES',
  'FORNICATED',
  'FORNICATES',
  'FRANCHISED',
  'FRUITCAKES',
  'FULMINATED',
  'FULMINATES',
  'FUMIGATORS',
  'GELATINOUS',
  'GLAMORIZED',
  'GLAMOURIZE', //OK
  'GODFATHERS', //OK
  'GODPARENTS', //OK
  'GOLDBRICKS', //OK
  'GRACIOUSLY',
  'GREYHOUNDS',
  'GRIEVOUSLY',
  'GROUCHIEST',
  'HANDSOMELY',
  'HARLEQUINS', //OK
  'HARVESTING', //OK
  'HEADSTRONG',
  'HOLSTERING',
  'HOSPITABLE',
  'HOSPITABLY',
  'HOUSEPLANT',
  'HUMANIZERS',
  'HUMDINGERS',
  'HUMPBACKED',
  'HYDRAULICS',
  'HYDROPLANE', //OK
  'HYPERBOLAS',
  'HYPERBOLIC',
  'HYPNOTIZED', //OK
  'HYPNOTIZES',
  'HYPOCRITES',
  'HYPODERMIC',
  'HYSTERICAL',
  'IDEOGRAPHS',
  'IMPERSONAL',
  'IMPORTANCE',
  'IMPORTUNED',
  'IMPORTUNES',
  'IMPROVABLE',
  'IMPUDENTLY',
  'INCUBATORS',
  'INCULPATED',
  'INCULPATES',
  'INCURABLES',
  'INEXORABLY',
  'INFAMOUSLY',
  'INOCULATED',
  'INOCULATES',
  'INTERLOCKS',
  'INTRODUCES',
  'JOCULARITY',
  'JOURNALISM',
  'JOURNALIST', //OK
  'JUDGMENTAL',
  'JUDGMENTAL', //OK
  'JUXTAPOSED',
  'KOHLRABIES',
  'LABYRINTHS',
  'LACQUERING',
  'LADYFINGER', //OK
  'LANGUISHED',
  'LAWRENCIUM',
  'LENGTHWAYS',
  'LIFEGUARDS',
  'LOGARITHMS',
  'LONGITUDES',
  'LOVEMAKING', //OK
  'LUMBERJACK', //OK
  'LYMPHATICS',
  'MACKINTOSH', //OK
  'MAGNITUDES',
  'MANIFESTLY',
  'MANUSCRIPT', //OK
  'MATCHBOXES',
  'MAYFLOWERS',
  'MENDACIOUS',
  'METHODICAL',
  'MICROWAVED',
  'MICROWAVES',
  'MINERALOGY',
  'MISCOUNTED',
  'MISFORTUNE', //OK
  'MISTAKENLY',
  'MODERATING',
  'MODULATING',
  'MONARCHIES',
  'MONARCHIST', //OK
  'MONETARILY',
  'MOTHERLAND', //OK
  'MUDSLINGER',
  'NEIGHBORLY',
  'NIGHTCLUBS', //OK
  'NIGHTMARES', //OK
  'NORMALIZED',
  'NORMALIZES',
  'NOTICEABLY',
  'OBDURATELY',
  'OBFUSCATED',
  'OSTRACIZED',
  'OUTFLANKED',
  'OUTLANDISH',
  'OUTPLAYING',
  'OUTWEARING',
  'OVERACTING',
  'OVERLAYING',
  'OVERNIGHTS',
  'OVERPAYING',
  'OVERTAKING',
  'OVERTAXING',
  'PACHYDERMS',
  'PADLOCKING',
  'PAINTBRUSH', //OK
  'PALINDROME', //OK
  'PANEGYRICS',
  'PARCHMENTS',
  'PARQUETING',
  'PATCHWORKS',
  'PATHFINDER', //OK
  'PATHOGENIC',
  'PATRONIZED',
  'PATRONIZES',
  'PATRONYMIC',
  'PAUNCHIEST',
  'PERSUADING',
  'PHILANDERS',
  'PHLEGMATIC',
  'PITCHFORKS',
  'PLASTERING',
  'PLATFORMED',
  'PLAYGROUND',
  'PLAYGROUND', //OK
  'PLAYTHINGS',
  'PLAYWRIGHT',
  'PLEASURING',
  'POCKETFULS',
  'POLYTHEISM',
  'PREAMBLING',
  'PRECAUTION',
  'PRECAUTION', //OK
  'PRECIOUSLY',
  'PRECLUDING',
  'PRECLUSION',
  'PREVIOUSLY',
  'PROCLAIMED',
  'PRODUCTIVE',
  'PROFITABLE',
  'PROFITABLY',
  'PROFLIGACY',
  'PROFLIGATE',
  'PROFUNDITY',
  'PROJECTING',
  'PROMULGATE',
  'PROSCENIUM', //OK
  'PURCHASING',
  'PURGATIVES',
  'PUTREFYING',
  'QUADRICEPS',
  'RANDOMIZES',
  'RAUNCHIEST',
  'RAVENOUSLY',
  'RAVISHMENT',
  'REDOUBLING',
  'REDUCTIONS',
  'REFOCUSING',
  'REGULATION',
  'REGULATION', //OK
  'RELOCATING',
  'REPUBLICAN', //OK
  'RESTOCKING',
  'RESTUDYING',
  'RESUMPTION',
  'RETOUCHING',
  'RHAPSODIZE',
  'RHEUMATICS',
  'ROUGHNECKS',
  'ROUNDELAYS',
  'SCAMPERING',
  'SCATHINGLY',
  'SCHEDULING',
  'SCRAMBLING',
  'SHOCKINGLY',
  'SHOPLIFTER', //OK
  'SHRINKABLE',
  'SLATHERING',
  'SLUMBERING',
  'SMOLDERING',
  'SMOTHERING',
  'SOUNDTRACK',
  'SPECULATOR',
  'SPHEROIDAL',
  'SPLOTCHIER',
  'SPLOTCHING',
  'SQUELCHING',
  'STAMPEDING',
  'STEWARDING',
  'STOCKADING',
  'STOCKPILED',
  'STOMACHING',
  'STUPEFYING',
  'SUBHEADING',
  'SUBJECTING',
  'SUBJECTION',
  'SUBLIMATED',
  'SUBTRAHEND',
  'SUBVERTING',
  'SUPERWOMAN', //OK
  'SWITCHABLE',
  'SYMBOLIZED',
  'SYMPATHIZE',
  'SYNCOPATED',
  'TAMBOURINE',
  'THROWBACKS',
  'THUMBSCREW',
  'TIMBERLAND',
  'TOUCHINGLY',
  'TOURMALINE',
  'TRAMPOLINE', //OK
  'TRANSFIXED',
  'TRAPEZOIDS',
  'TRAVELINGS',
  'TRUCKLOADS',
  'TUMBLEDOWN',
  'ULCERATING',
  'ULCERATION',
  'ULTRASONIC', //OK
  'UNDERCOATS',
  'UNDERPLAYS',
  'UNGODLIEST',
  'UNSCRAMBLE',
  'UNSOCIABLE',
  'UNSTEADILY',
  'UNWORKABLE',
  'UPHOLSTERY',
  'VIBRAPHONE', //OK
  'VOLKSWAGEN', //OK
  'WANDERLUST',
];
