export const WORDS_10LETTERSUNIQUE_COOL_EN = [

  'AFTERSHOCK', //OK
  'ALGORITHMS', //OK
  'AMPLITUDES', //OK
  'BACKGROUND', //OK
  'BEACHFRONT', //OK
  'BENCHMARKS', //OK
  'BINOCULARS', //OK
  'BLACKSMITH', //OK
  'BLUEPRINTS', //OK
  'BREAKPOINT', //OK
  'BUTCHERING', //OK
  'CAMPGROUND', //OK
  'CHIVALROUS', //OK
  'CLIPBOARDS', //OK
  'CLOTHESPIN', //OK
  'COMBATHELP', //OK
  'COMPATIBLE', //OK
  'CORNFLAKES', //OK
  'CREMATIONS', //OK
  'CUMBERLAND', //OK
  'CYBERPUNKS', //OK
  'DEATHBLOWS', //OK
  'DECATHLONS', //OK
  'DEFOLIANTS', //OK
  'DESTROYING', //OK
  'DUMBWAITER', //OK
  'EARTHLINGS', //OK
  'EXHAUSTION', //OK
  'FUMIGATORS', //OK
  'GODFATHERS', //OK
  'GOLDBRICKS', //OK
  'GREYHOUNDS', //OK
  'HARLEQUINS', //OK
  'HARVESTING', //OK
  'HOUSEPLANT', //OK
  'HYDROPLANE', //OK
  'IDEOGRAPHS', //OK
  'IMPERSONAL', //OK
  'INCUBATORS', //OK
  'JUDGMENTAL', //OK
  'JUXTAPOSED', //OK
  'LADYFINGER', //OK
  'LADYFINGER', //OK
  'LIFEGUARDS', //OK
  'LOVEMAKING', //OK
  'LUMBERJACK', //OK
  'MANUSCRIPT', //OK
  'MATCHBOXES', //OK
  'MICROWAVES', //OK
  'MISFORTUNE', //OK
  'MONARCHIES', //OK
  'MOTHERLAND', //OK
  'MUDSLINGER', //OK
  'NIGHTCLUBS', //OK
  'NIGHTMARES', //OK
  'OBFUSCATED', //OK
  'OUTFLANKED', //OK
  'OVERACTING', //OK
  'OVERPAYING', //OK
  'OVERTAXING', //OK
  'PAINTBRUSH', //OK
  'PALINDROME', //OK
  'PATHFINDER', //OK
  'PATHOGENIC', //OK
  'PHILANDERS', //OK
  'PITCHFORKS', //OK
  'PLAYGROUND', //OK
  'PLEASURING', //OK
  'PRECAUTION', //OK
  'PROSCENIUM', //OK
  'QUADRICEPS', //OK
  'RANDOMIZES', //OK
  'RAVISHMENT', //OK
  'REGULATION', //OK
  'REPUBLICAN', //OK
  'RHEUMATICS', //OK
  'SCRAMBLING', //OK
  'SHOPLIFTER', //OK
  'SLUMBERING', //OK
  'SQUELCHING', //OK
  'STOCKPILED', //OK
  'SUPERWOMAN', //OK
  'SWITCHABLE', //OK
  'TAMBOURINE', //OK
  'TIMBERLAND', //OK
  'TRAMPOLINE', //OK
  'TRAPEZOIDS', //OK
  'ULTRASONIC', //OK
  'UNDERCOATS', //OK
  'UPHOLSTERY', //OK
  'VIBRAPHONE', //OK
  'VOLKSWAGEN', //OK
];

export const WORDS10UNIQUE_ALL_PL = [
  'ALGORITHMS',
  'ARTICHOKES',
  'AFTERSHOCK', //OK
  'AMPLITUDES', //OK
  'BACKGROUND', //OK
  'BACKSLIDER',
  'BANDOLIERS',
  'BANKRUPTCY',
  'BEACHFRONT',
  'BENCHMARKS',
  'BINOCULARS', //OK
  'BIRTHPLACE',
  'BLACKSMITH', //OK
  'BLACKTHORN',
  'BLOCKADING',
  'BLOCKHEADS',
  'BLUEPRINTS', //OK
  'BLUSTERING',
  'BOLSTERING',
  'BOULEVARDS',
  'BOUNDARIES',
  'BOYFRIENDS',
  'BRACKETING',
  'BREAKDOWNS',
  'BREAKPOINT', //OK
  'BRUTALIZED',
  'BRUTALIZES',
  'BUTCHERING', //OK
  'BYPRODUCTS',
  'CAMPGROUND', //OK
  'CENTIGRAMS',
  'CHAIRWOMEN',
  'CHAMPIONED',
  'CHARMINGLY',
  'CHIVALROUS', //OK
  'CHLORINATE',
  'CLAMBERING',
  'CLAMPDOWNS',
  'CLIPBOARDS', //OK
  'CLOTHESPIN',
  'CLOTHESPIN',
  'CLUSTERING',
  'COLUMBINES',
  'COMBATHELP', //OK
  'COMPATIBLE',
  'COMPATIBLY',
  'COMPLAINED',
  'COMPLAINER',
  'COMPLAINTS',
  'COMPLETING',
  'COMPLEXITY',
  'COMPULSIVE',
  'CONFIGURED',
  'CONFIGURES',
  'CONFUSEDLY',
  'CONJUGATED',
  'CONJUGATES',
  'CONSUMABLE',
  'COPULATING',
  'COPYRIGHTS',
  'CORNFLAKES', //OK
  'CREDITABLY',
  'CREMATIONS', //OK
  'CRUMBLIEST',
  'CRYSTALIZE',
  'CULMINATED',
  'CULMINATES',
  'CUMBERLAND',
  'CURTSEYING',
  'CUSTOMIZED',
  'CYBERPUNKS', //OK
  'DAVENPORTS',
  'DEATHBLOWS', //OK
  'DEBAUCHING',
  'DEBONAIRLY',
  'DECATHLONS', //OK
  'DECORATING',
  'DEFAULTING',
  'DEFOLIANTS',
  'DEFROSTING',
  'DEMOGRAPHY',
  'DEPILATORY',
  'DESOLATING',
  'DESPICABLY',
  'DESTROYING', //OK
  'DEXTROUSLY',
  'DISBARMENT',
  'DISCOURAGE',
  'DISGRUNTLE',
  'DISHARMONY',
  'DISPATCHER',
  'DISPUTABLE',
  'DOWNSTREAM',
  'DUMBWAITER',
  'DUMBWAITER',
  'DUPLICATES',
  'DUPLICATOR',
  'EARTHLINGS', //OK
  'EDUCATIONS',
  'EMULATIONS',
  'EPISTOLARY',
  'EXACTINGLY',
  'EXHAUSTING',
  'EXHAUSTION', //OK
  'EXHUMATION',
  'FALTERINGS',
  'FARSIGHTED',
  'FARSIGHTED',
  'FETCHINGLY',
  'FLAMINGOES',
  'FLAMINGOES',
  'FLAVORINGS',
  'FLOURISHED',
  'FLUORIDATE',
  'FLUSTERING',
  'FLYWEIGHTS',
  'FORGIVABLE',
  'FORMALIZED',
  'FORMALIZES',
  'FORMIDABLE',
  'FORMIDABLY',
  'FORMULATED',
  'FORMULATES',
  'FORNICATED',
  'FORNICATES',
  'FRANCHISED',
  'FRUITCAKES',
  'FULMINATED',
  'FULMINATES',
  'FUMIGATORS', //OK
  'GELATINOUS',
  'GLAMORIZED',
  'GLAMOURIZE',
  'GODFATHERS', //OK
  'GODPARENTS',
  'GOLDBRICKS', //OK
  'GRACIOUSLY',
  'GREYHOUNDS', //OK
  'GRIEVOUSLY',
  'GROUCHIEST',
  'HANDSOMELY',
  'HARLEQUINS', //OK
  'HARVESTING', //OK
  'HEADSTRONG',
  'HOLSTERING',
  'HOSPITABLE',
  'HOSPITABLY',
  'HOUSEPLANT', //OK
  'HUMANIZERS',
  'HUMDINGERS',
  'HUMPBACKED',
  'HYDRAULICS',
  'HYDROPLANE', //OK
  'HYPERBOLAS',
  'HYPERBOLIC',
  'HYPNOTIZED',
  'HYPNOTIZES',
  'HYPOCRITES',
  'HYPODERMIC',
  'HYSTERICAL',
  'IDEOGRAPHS', //OK
  'IMPERSONAL', //OK
  'IMPORTANCE',
  'IMPORTUNED',
  'IMPORTUNES',
  'IMPROVABLE',
  'IMPUDENTLY',
  'INCUBATORS', //OK
  'INCULPATED',
  'INCULPATES',
  'INCURABLES',
  'INEXORABLY',
  'INFAMOUSLY',
  'INOCULATED',
  'INOCULATES',
  'INTERLOCKS',
  'INTRODUCES',
  'JOCULARITY',
  'JOURNALISM',
  'JOURNALIST',
  'JUDGMENTAL',
  'JUDGMENTAL',
  'JUXTAPOSED', //OK
  'KOHLRABIES',
  'LABYRINTHS',
  'LACQUERING',
  'LADYFINGER', //OK
  'LANGUISHED',
  'LAWRENCIUM',
  'LENGTHWAYS',
  'LIFEGUARDS', //OK
  'LOGARITHMS',
  'LONGITUDES',
  'LOVEMAKING',
  'LUMBERJACK', //OK
  'LYMPHATICS',
  'MACKINTOSH',
  'MAGNITUDES',
  'MANIFESTLY',
  'MANUSCRIPT', //OK
  'MATCHBOXES', //OK
  'MAYFLOWERS',
  'MENDACIOUS',
  'METHODICAL',
  'MICROWAVED',
  'MICROWAVES', //OK
  'MINERALOGY',
  'MISCOUNTED',
  'MISFORTUNE',
  'MISTAKENLY',
  'MODERATING',
  'MODULATING',
  'MONARCHIES', //OK
  'MONARCHIST',
  'MONETARILY',
  'MOTHERLAND', //OK
  'MUDSLINGER', //OK
  'NEIGHBORLY',
  'NIGHTCLUBS', //OK
  'NIGHTMARES', //OK
  'NORMALIZED',
  'NORMALIZES',
  'NOTICEABLY',
  'OBDURATELY',
  'OBFUSCATED', //OK
  'OSTRACIZED',
  'OUTFLANKED', //OK
  'OUTLANDISH',
  'OUTPLAYING',
  'OUTWEARING',
  'OVERACTING', //OK
  'OVERLAYING',
  'OVERNIGHTS',
  'OVERPAYING', //OK
  'OVERTAKING',
  'OVERTAXING', //OK
  'PACHYDERMS',
  'PADLOCKING',
  'PAINTBRUSH', //OK
  'PALINDROME', //OK
  'PANEGYRICS',
  'PARCHMENTS',
  'PARQUETING',
  'PATCHWORKS',
  'PATHFINDER', //OK
  'PATHOGENIC', //OK
  'PATRONIZED',
  'PATRONIZES',
  'PATRONYMIC',
  'PAUNCHIEST',
  'PERSUADING',
  'PHILANDERS', //OK
  'PHLEGMATIC',
  'PITCHFORKS', //OK
  'PLASTERING',
  'PLATFORMED',
  'PLAYGROUND',
  'PLAYGROUND', //OK
  'PLAYTHINGS',
  'PLAYWRIGHT',
  'PLEASURING', //OK
  'POCKETFULS',
  'POLYTHEISM',
  'PREAMBLING',
  'PRECAUTION',
  'PRECAUTION', //OK
  'PRECIOUSLY',
  'PRECLUDING',
  'PRECLUSION',
  'PREVIOUSLY',
  'PROCLAIMED',
  'PRODUCTIVE',
  'PROFITABLE',
  'PROFITABLY',
  'PROFLIGACY',
  'PROFLIGATE',
  'PROFUNDITY',
  'PROJECTING',
  'PROMULGATE',
  'PROSCENIUM', //OK
  'PURCHASING',
  'PURGATIVES',
  'PUTREFYING',
  'QUADRICEPS', //OK
  'RANDOMIZES', //OK
  'RAUNCHIEST',
  'RAVENOUSLY',
  'RAVISHMENT', //OK
  'REDOUBLING',
  'REDUCTIONS',
  'REFOCUSING',
  'REGULATION',
  'REGULATION', //OK
  'RELOCATING',
  'REPUBLICAN',
  'RESTOCKING',
  'RESTUDYING',
  'RESUMPTION',
  'RETOUCHING',
  'RHAPSODIZE',
  'RHEUMATICS', //OK
  'ROUGHNECKS',
  'ROUNDELAYS',
  'SCAMPERING',
  'SCATHINGLY',
  'SCHEDULING',
  'SCRAMBLING', //OK
  'SHOCKINGLY',
  'SHOPLIFTER', //OK
  'SHRINKABLE',
  'SLATHERING',
  'SLUMBERING', //OK
  'SMOLDERING',
  'SMOTHERING',
  'SOUNDTRACK',
  'SPECULATOR',
  'SPHEROIDAL',
  'SPLOTCHIER',
  'SPLOTCHING',
  'SQUELCHING', //OK
  'STAMPEDING',
  'STEWARDING',
  'STOCKADING',
  'STOCKPILED', //OK
  'STOMACHING',
  'STUPEFYING',
  'SUBHEADING',
  'SUBJECTING',
  'SUBJECTION',
  'SUBLIMATED',
  'SUBTRAHEND',
  'SUBVERTING',
  'SUPERWOMAN', //OK
  'SWITCHABLE', //OK
  'SYMBOLIZED',
  'SYMPATHIZE',
  'SYNCOPATED',
  'TAMBOURINE', //OK
  'THROWBACKS',
  'THUMBSCREW',
  'TIMBERLAND', //OK
  'TOUCHINGLY',
  'TOURMALINE',
  'TRAMPOLINE', //OK
  'TRANSFIXED',
  'TRAPEZOIDS', //OK
  'TRAVELINGS',
  'TRUCKLOADS',
  'TUMBLEDOWN',
  'ULCERATING',
  'ULCERATION',
  'ULTRASONIC', //OK
  'UNDERCOATS', //OK
  'UNDERPLAYS',
  'UNGODLIEST',
  'UNSCRAMBLE',
  'UNSOCIABLE',
  'UNSTEADILY',
  'UNWORKABLE',
  'UPHOLSTERY', //OK
  'VIBRAPHONE', //OK
  'VOLKSWAGEN', //OK
  'WANDERLUST',
];
