name: Deploy to GitHub Pages via angular-cli-ghpages

on:
  push:
    branches:
    - yamltest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: radio-operator-toolbox-angular
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Version and build UP
      run: 
        jq '.build=(now | strflocaltime("%Y%m%d.%H%M"))' package.json > package.json.tmp 
        && mv package.json.tmp package.json
        && echo "build:" && jq -r '.build' package.json

    - name: Prepare and deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm install
        npm run ng -- deploy --base-href=/RadioOperatorToolbox/ --name="KubaMiszcz" --email="zielonyeufor@gmail.com" --no-silent
        echo "[SUCCESS] build:" && jq -r '.build' package.json
