name: Deploy to GitHub Pages via angular-cli-ghpages

on:
  push:
    branches:
    - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Prepare and deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm install
        npm run ng -- deploy --base-href=/ShootingTrainer/ --name="KubaMiszcz" --email="zielonyeufor@gmail.com" --no-silent